### ISSUE TITLE
gatsby program is missing to run npm tasks

### ISSUE THREAD

**Issue by rapenne-s** [tweag/nickel-lang.org#393]
**Describe the bug**

It's not possible to use `npm run develop` or `npm run build` as suggested by the text displayed when using `nix develop`

```
solene@x1 ~/d/nickel-lang.org (master) [127]> nix develop
warning: Using saved setting for 'extra-substituters = https://tweag-nickel.cachix.org' from ~/.local/share/nix/trusted-settings.json.
warning: Using saved setting for 'extra-trusted-public-keys = tweag-nickel.cachix.org-1:GIthuiK4LRgnW64ALYEoioVUQBWs0jexyoYVeLDBwRA=' from ~/.local/share/nix/trusted-settings.json.
ln: failed to create symbolic link 'src/nickel-manual': File exists
== Run `npm run develop` to start developing
 or
== Run `npm run build` to build the website
(nix:nix-shell) bash-5.1$ npm run develop

> nickel-lang.org@1.0.0 develop
> gatsby develop

sh: line 1: gatsby: command not found
(nix:nix-shell) bash-5.1$ 
```

**Expected behavior**
`gatsby` should be provided by nix?

**Environment**
 - OS name + version: NixOS 22.11
 - Version of the code: 0b9e8d4a6c848901152fd5c1557fec132b48ca9a

**Additional context**

using `npm install gatsby` solves the problem

**Comment by yannham** [comment]
I think you have to `npm install` before anything. The build isn't really nixified fully, it just provides the nickel wasm repl and nodejs, but otherwise the website relies on npm to build. In a fresh project you first need to do an `npm install` to retrieve the packages described by package.json. For example the workflow deploy use `npm ci` (which is similar but specialized for CI).

It could be documented though, as there is absolutely no documentation for the time being...

**Comment by yannham** [comment]
Unless I'm missing something, gatsby is not missing if one does `npm install` before. let's open a separate issue if there is a documentation problem.
